on: 
  push:
    branches:
      - '**'
  pull_request:
  release:
    types: [released]

name: Configure, Build, Test, Create and Upload library

jobs:
  configure:
    name: Configure, Build, Test, Create and Upload library
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install Conan
      uses: turtlebrowser/get-conan@main
    - name: Add artifactory remote
      run: conan remote add jothepro-conan-public https://jothepro.jfrog.io/artifactory/api/conan/conan-public
    - name: Install dependencies
      run: conan install .
    - name: configure, build, test and create project
      run: conan create .
    - name: login to artifactory
      if: github.event_name == 'release'
      run: conan user github -p ${{ env.CONAN_PASSWORD }} -r=jothepro-conan-public
    - name: upload to artifactory
      if: github.event_name == 'release'
      run: conan upload mylibrary -r=jothepro-conan-public --confirm